server:
  port: 8081

spring:
  application:
    name: minicloud-worker

# Worker-specific configuration
minicloud:
  worker:
    id: ${WORKER_ID:worker-1}

# Management and monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Logging configuration
logging:
  level:
    com.minicloud: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"